[package]
name = "brenchain"
version = "0.1.0"
authors = ["brenetic <b@brenetic.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
